### ISSUE TITLE
Simulation on OS X El Capitan not working

### ISSUE THREAD

**Issue by rjboczar** [studywolf/control#1]
On your [related blog post](https://studywolf.wordpress.com/2016/02/03/the-iterative-linear-quadratic-regulator-method/) you stated that running the Python version with a command like

`python2 run.py arm2_python ilqr reach`

should work. Running this command throws errors about importing the py2LinkArm.so file.

**Comment by studywolf** [comment]
Ah! Had an `import py2linkarm` that shouldn't have been there, can you pull `master` and try again? I just committed removing that import from `arm2base`, which hopefully will take care of it!

**Comment by rjboczar** [comment]
I think now it's choking on the `import py2linkarm` from `arm.py`?

**Comment by studywolf** [comment]
ah! there were some unnecessary imports in the `ilqr.py`. I pushed another commit, could you pull and try again?

**Comment by rjboczar** [comment]
That appears to fix it, but now the problem is unrelated issues with animations on OS X referenced [here](https://github.com/matplotlib/matplotlib/issues/531). I'll try to hack around and if I can get it to work I'll submit a pull thingy. Thanks!

**Comment by studywolf** [comment]
That would be great! I'm only ever on linux so I don't really get the chance to test things on OS X, hopefully it's not too painful to fix!

**Comment by ericmjonas** [comment]
Replying to @rjboczar, you can get the animations working under OSX with conda if you add 

```
import matplotlib
matplotlib.use('TkAgg')
```

to the top of `sim_and_plot.py` 
which switches to a TK backend.

**Comment by studywolf** [comment]
Ah awesome, thanks for the tip @ericmjonas!
