### ISSUE TITLE
Error: numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by deepakraina99** [studywolf/control#11]
I am getting the error on running the following code inside the two_link arm folder:

```python setup.py build_ext -i```

Error: numpy/arrayobject.h: No such file or directory

**Comment by studywolf** [comment]
I was able to recreate this and then fix it by adding an import in the setup file. If you pull from master again and run this it should be fixed!

**Comment by studywolf** [comment]
Please lmk if it doesn't work for you

**Comment by deepakraina99** [comment]
It worked. Thanks for your support.
