### ISSUE TITLE
Questions on (py)DMP Implementation

### ISSUE THREAD

**Issue by pranshumalik14** [studywolf/control#13]
We have been following your pymdps and the current (control) GitHub repositories to understand how DMPs work, and we have a few questions we have not been able to answer yet:

- For multi-joint arms, what is the input trajectory for training?
- We noticed the code (in this repository) only involves trajectories for the end-effector in world coordinates. However, it is able to train the DMPs for all joints. Is this where OSC was involved? If yes, then can we instead give all joint coordinates (in angles, instead of world coordinates) as training input and train the DMPs using the same code (without major adjustments)? We are thinking of doing this so that it is easier to directly apply forcing functions (as qdotdot) to the robot joints, and perhaps not involve OSC to infer those from only the end-effector motion in world coordinates.
- We were assuming that only the end-effector trajectory is passed in for training the DMPs. However, in that case, when are joint trajectories calculated, if our interpretation of OSC, as above, is incorrect?

Any help or pointers on this will be highly appreciated!

**Comment by studywolf** [comment]
Responded in email!

**Comment by pranshumalik14** [comment]
Yes, thanks a lot!
