### ISSUE TITLE
There is no setup.py file

### ISSUE THREAD

**Issue by mjm522** [studywolf/control#2]
Hi Travis,

I couldn't find the `setup.py` file in the repository. I am on  a mac and and getting the following error.
`~/control/studywolf_control/arms/two_link/py2LinkArm.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00`, I guess I will have to build it. Hence asked.

**Comment by studywolf** [comment]
Hi,

I would guess that you're trying to run the file that I compiled for
Ubuntu, you if you change it so that you run using 'arm2_python' it should
work!
Let me know!
Cheers,
