### ISSUE TITLE
Is this run by the control code you wrote?

### ISSUE THREAD

**Issue by wonchul-kim** [studywolf/control#7]
I'm studying dmp through your posts.

I've read the first dmp post and code.
Those are really helpful to me and so, thank you!

For the 2nd dmp post, I read and to see the code I download this git.
However, I am wondering if there is no dmp code you wrote, in this git you just use the library(pydmps), right?

**Comment by studywolf** [comment]
correct! actually there's also a more recent version of all this code up at https://github.com/abr/abr_control, and you can find an example of it using the pydmps library here:https://github.com/abr/abr_control/blob/master/examples/PyGame/dmps_path_planning.py

i need to update the readme here to point towards that repo, actually. thanks!

**Comment by wonchul-kim** [comment]
I have no idea about pydmps and thus, i want to ask that
in the first dmp post, there is pydmps you wrote including cs.py, dmp.py, dmp_discrete.py and so on.

In this git, it doesn't use those codes?

Then, pydmps is another official library which is different to those you wrote in the first dmp post?

I am just confusing since those are same name...

**Comment by studywolf** [comment]
hm, i'm not sure what you're referring to. I believe all the blog post links link to the repo https://github.com/studywolf/pydmps which is what generated the pydmps library you can pip install...

**Comment by wonchul-kim** [comment]
hmm,, I mean ,,
I just wonder that in this git, the control code is run by pydmps and this pydmps is what you generated in the first dmp post, right?

**Comment by studywolf** [comment]
ah, pydmps is an extension of the code from my first blog post, yup!

**Comment by wonchul-kim** [comment]
Thank you!

I just want to know which control code I have to see and study.

**Comment by studywolf** [comment]
you're welcome! good luck!
